CREATE TABLE "Registration" (
    id SERIAL PRIMARY KEY,
    "emailId" VARCHAR(255) NOT NULL,
    "voiceName" VARCHAR(255),
    "participantName" VARCHAR(255) NOT NULL,
    whatsapp VARCHAR(255),
    "parentTemple" VARCHAR(255),
    "counselorName" VARCHAR(255),
    "campName" VARCHAR(255) NOT NULL,
    "firstMealDate" INTEGER NOT NULL,
    "firstMealType" VARCHAR(255) NOT NULL,
    "lastMealDate" INTEGER NOT NULL,
    "lastMealType" VARCHAR(255) NOT NULL,
    "dinnerType" VARCHAR(255) NOT NULL,
    accommodation VARCHAR(255) NOT NULL,
    gender VARCHAR(255) NOT NULL,
    "participantType" VARCHAR(255),
    age INTEGER,
    "marriedSinceYear" INTEGER,
    "pocName" VARCHAR(255) NOT NULL,
    "pocContact" VARCHAR(255) NOT NULL,
    "paymentId" VARCHAR(255),
    "deductionSource" VARCHAR(255),
    passcode VARCHAR(255),
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    amount REAL NOT NULL,
    entrycost REAL
);
